support php 8.4
phparkitect/arkitect pull request #441
Opened 2024-11-26 09:11 UTC by nikow13

2024-12-13 06:15 UTC, AlessandroMinoccheri commented
Hello @nikow13!
Thanks for your contribution, we need to wait psalm I think to see if all tests will be green

2025-01-21 15:00 UTC, damien-louis commented
Related psalm issue and MR about PHP 8.4 support: 
https://github.com/vimeo/psalm/issues/11107
https://github.com/vimeo/psalm/pull/10928

2025-01-27 11:31 UTC, ostrolucky commented
Psalm 6 has been released which supports php 8.4

2025-01-31 05:38 UTC, akondas commented
ready to go?

2025-02-04 16:43 UTC, ostrolucky commented
looks like php version used for running scrutinizer needs to be bumped

2025-02-04 17:11 UTC, nikow13 commented
> looks like php version used for running scrutinizer needs to be bumped

Yes, it seems Scrutinizer is managed outside the code, so I can’t update it

2025-02-04 18:06 UTC, damien-louis commented
Poke @AlessandroMinoccheri

2025-02-05 08:11 UTC, AlessandroMinoccheri commented
We are verifying it :)

2025-02-05 21:27 UTC, AlessandroMinoccheri commented on Dockerfile
> +ARG PHP_VERSION=8.4
Why the version 8.4 and not the minor that we can support?

2025-02-06 08:09 UTC, nikow13 commented on Dockerfile
> +ARG PHP_VERSION=8.4
for local testing with the last version

2025-02-06 22:34 UTC, micheleorselli requested changes
Talking a bit with @AlessandroMinoccheri we agreed php 7 support can be dropped, but we would like to keep support for php 8.0 on

2025-02-06 22:34 UTC, micheleorselli commented on .github/workflows/build.yml
> +        php-versions: [ '8.2', '8.3', '8.4']
we'd like to keep compatibility from php 8.0

2025-02-06 22:34 UTC, micheleorselli commented on .github/workflows/build.yml
> +          php-version: 8.4
shouldn't we use the smaller supported version (8.0)?

2025-02-06 22:34 UTC, micheleorselli commented on .github/workflows/build.yml
> +    runs-on: ubuntu-latest
would that mean when ubuntu gets upgraded we automatically get the latest version? If that the case an approach where we explicitly set the version is preferred imo

2025-02-06 22:34 UTC, micheleorselli commented on .github/workflows/build.yml
> +        php-versions: [ '8.2', '8.3', '8.4' ]
same as above

2025-02-06 22:34 UTC, micheleorselli commented on Dockerfile
> +ARG PHP_VERSION=8.4
that should be the smaller supported version maybe? Like 8.0 🤔

2025-02-06 22:34 UTC, micheleorselli commented on tests/Unit/Expressions/ForClasses/ResideInOneOfTheseNamespacesTest.php
> +    public function test_it_should_match_namespace_and_descendants(string $expectedNamespace, string $actualFQCN, string $explanation): void
`@param` in phpdoc does not match with the method signature, would it be possibile to remove it?

2025-02-06 22:34 UTC, micheleorselli commented on src/CLI/TargetPhpVersion.php
> +        '8.4',
iirc here we are defining which version arkitect is capable of parsing. Should we keep versions older than 8.0? if yes, should then keep testing them (at least smoke test the phar) to be sure we are actually able to do so?

2025-02-06 22:34 UTC, micheleorselli commented on src/CLI/Progress/ProgressBarProgress.php
> +    private \Symfony\Component\Console\Output\NullOutput|OutputInterface $output;
isn't NullOutput implementing OutputInterface? If yes, that could be just 

`private OutputInterface $output;`

2025-02-07 09:51 UTC, nikow13 commented
> Talking a bit with @AlessandroMinoccheri we agreed php 7 support can be dropped, but we would like to keep support for php 8.0 on

Hi,
There are a lot of inconsistencies between different PHP versions. I couldn't get it to work with 8.0 and 8.1, but feel free to give it a try if you have any ideas !

2025-02-13 22:45 UTC, micheleorselli commented
hey there, that should be fixed by #447

2025-02-13 23:48 UTC, closed without merging